CREATE TABLE flight (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(255),
    airline VARCHAR(255),
    source VARCHAR(255),
    destination VARCHAR(255),
    total_seats INT NOT NULL,
    available_seats INT NOT NULL,
    price DOUBLE PRECISION NOT NULL
);