CREATE TABLE passenger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    age INT NOT NULL,
    contact VARCHAR(255) DEFAULT NULL,
    created_by VARCHAR(255) DEFAULT NULL
);

CREATE TABLE booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL,
    passenger_id BIGINT NOT NULL,
    booking_date DATE DEFAULT NULL,
    created_by VARCHAR(255) DEFAULT NULL,

    CONSTRAINT fk_booking_passenger
        FOREIGN KEY (passenger_id)
        REFERENCES passenger (id)
);

CREATE INDEX idx_booking_flight_id
    ON booking (flight_id);

CREATE INDEX idx_booking_passenger_id
    ON booking (passenger_id);

CREATE INDEX idx_booking_created_by
    ON booking (created_by);

CREATE INDEX idx_passenger_created_by
    ON passenger (created_by);